wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "ClipMapTerrainShader.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "FXAAShader.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "WaterShader.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "ClipMapShader.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/RenderGBuffer.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/ClearGBuffer.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/DirectionalLight.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/PointLight.fx" /Fo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/CombineFinal.fx" /Fo
