wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "FXAAShader.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "WaterShader.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/RenderGBuffer.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/ClearGBuffer.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/DirectionalLight.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/PointLight.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "gbuffer/CombineFinal.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "SkyShader.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "SSAOShader.fx" /Fo /nologo
wine64 "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64\fxc.exe" /Tfx_2_0 "ShadowMapShader.fx" /Fo /nologo
